web-task-10-django/task_10/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<int:id_>', views.show_author, name='root_author'),
    path('add_author', views.add_author, name='add_author'),
    path('add_quote', views.add_quote, name='add_quote'),
    path('add_tag', views.add_tag, name='add_tag'),
]

web-task-10-django/task_10/task_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

web-task-10-django/task_10/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

web-task-10-django/task_10/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

web-task-10-django/task_10/users/models.py
from django.db import models

# Create your models here.

web-task-10-django/task_10/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50, required=False, widget=TextInput())
    born_location = CharField(max_length=150, required=False, widget=TextInput())
    description = CharField(required=False, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.fullname

class QuoteForm(ModelForm):
    quote = CharField(max_length=500, required=True, widget=TextInput())
    author = MyModelChoiceField(queryset=Author.objects.all(), required=False, to_field_name="fullname")

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']

web-task-10-django/task_10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

web-task-10-django/task_10/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

from .models import Author, Quote, Tag

from .forms import AuthorForm, QuoteForm, TagForm
from .utils import get_mongodb
# Create your views here.


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def show_author(request, id_):
    author = Author.objects.get(id=id_)
    return render(request, 'quotes/author.html', context={'author': author})


def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='/')
        else:
            return render(request, 'quotes/add_author.html', {'form': form})

    return render(request, 'quotes/add_author.html', {'form': AuthorForm()})


def add_quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            return redirect(to='/')
        else:
            return render(request, 'quotes/add_quote.html', {'authors': authors, 'form': form, 'tags': tags})

    return render(request, 'quotes/add_quote.html', context={'authors': authors, 'form': QuoteForm(), 'tags': tags})


def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='/')
        else:
            return render(request, 'quotes/add_tag.html', {'form': form})

    return render(request, 'quotes/add_tag.html', {'form': TagForm()})

web-task-10-django/task_10/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='/')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='/')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='/')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='/')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='/')

web-task-10-django/task_10/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <div>Enter the author name:
            {{form.fullname}}
        </div>
        <span>{{ form.errors.fullname }}</span>
        <div>Enter the author born date:
            {{form.born_date}}
        </div>
        <span>{{ form.errors.born_date }}</span>
        <div>Enter the author born location:
            {{form.born_location}}
        </div>
        <span>{{ form.errors.born_location }}</span>
        <div>Enter the author description:
            {{form.description}}
        </div>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web-task-10-django/task_10/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>

        <div>Select author:
            {{form.author}}
        </div>

        <div> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>

    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web-task-10-django/task_10/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web-task-10-django/task_10/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-details">

    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>

</div>

{% endblock %}

web-task-10-django/task_10/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Django_task_10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">

            <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                {% if user.is_authenticated %}
                <h4>Welcome <b>{{ user.username }}!</b></h4>

                <a href="/add_quote" class="btn btn-success">Add Quote</a>
                <a href="/add_author" class="btn btn-success">Add Author</a>
                <a href="/add_tag" class="btn btn-success">Add Tag</a>

                <a href="{% url 'users:logout' %}" class="btn btn-warning">Logout</a>

                {% else %}

                <a href="{% url 'users:signup' %}" class="btn btn-warning">SignUp</a>
                <a href="{% url 'users:login' %}" class="btn btn-warning">Login</a>

                {% endif %}
            </nav>

        </div>
    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

web-task-10-django/task_10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load find_author %}
{% load find_tags %}

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author_id}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.id|tags %}
            <a class="tag" href="#">{{tag.name}}</a>
            {% endfor %}

        </div>
    </div>

    {% endfor %}

    <nav>
        <ul class="pager">

            <li class="previous pb-3">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>


            <li class="next pb-3">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">-></span> Next
                </a>
            </li>

        </ul>
    </nav>
    </div>

</div>

{% endblock %}

web-task-10-django/task_10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

web-task-10-django/task_10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}